// "Did you know?" — Haiti facts (English, Kreyòl, French). A different one shows each time someone logs in or opens the site.
window.LAKAYMWEN_DIDYOU = [
["Haiti became independent on January 1, 1804: the first Black republic in the world and the first free nation in Latin America and the Caribbean.",
 "Ayiti vin endepandan 1ye janvye 1804: premye repiblik nwa nan monn nan, e premye peyi lib nan Amerik Latin ak Karayib la.",
 "Haïti est devenue indépendante le 1er janvier 1804 : la première république noire du monde et la première nation libre d'Amérique latine et des Caraïbes."],
["The name “Haiti” comes from the Taíno word “Ayiti”, which means “land of high mountains”.",
 "Non “Ayiti” soti nan lang Tayino yo, li vle di “peyi ki gen anpil mòn”.",
 "Le nom « Haïti » vient du mot taïno « Ayiti », qui signifie « terre des hautes montagnes »."],
["Every January 1st, Haitians eat soup joumou to celebrate freedom. In 2021, UNESCO added it to its list of the world's cultural heritage.",
 "Chak 1ye janvye, Ayisyen manje soup joumou pou fete libète. An 2021, UNESCO mete l sou lis eritaj kiltirèl limanite.",
 "Chaque 1er janvier, les Haïtiens mangent la soupe joumou pour fêter la liberté. En 2021, l'UNESCO l'a inscrite au patrimoine culturel immatériel de l'humanité."],
["The Citadelle Laferrière, built by King Henri Christophe near Milot, is the largest fortress in the Americas and a UNESCO World Heritage Site.",
 "Sitadèl Laferyè, wa Anri Kristòf te bati toupre Milo, se pi gwo fò nan Amerik yo, e li sou lis Eritaj Mondyal UNESCO.",
 "La Citadelle Laferrière, construite par le roi Henri Christophe près de Milot, est la plus grande forteresse des Amériques et un site du patrimoine mondial de l'UNESCO."],
["Haiti's flag was created on May 18, 1803, in Arcahaie. That's why Haitians celebrate Flag Day every May 18.",
 "Drapo Ayiti te fèt 18 me 1803 nan Lakayè. Se pou sa Ayisyen fete Jou Drapo chak 18 me.",
 "Le drapeau haïtien a été créé le 18 mai 1803 à l'Arcahaie. C'est pourquoi les Haïtiens fêtent le Jour du Drapeau chaque 18 mai."],
["Haiti's motto, written on the flag, is “L'Union fait la force”: Unity is strength.",
 "Deviz Ayiti, ki ekri sou drapo a, se “L'Union fait la force”: Ansanm nou fò.",
 "La devise d'Haïti, inscrite sur le drapeau, est « L'Union fait la force »."],
["Kreyòl and French are Haiti's two official languages. Almost every Haitian speaks Kreyòl.",
 "Kreyòl ak franse se de lang ofisyèl Ayiti. Prèske tout Ayisyen pale kreyòl.",
 "Le créole et le français sont les deux langues officielles d'Haïti. Presque tous les Haïtiens parlent créole."],
["Pic la Selle, in the southeast, is Haiti's highest mountain at about 2,680 meters (8,790 feet).",
 "Pik La Sèl, nan Sidès, se pi wo mòn Ayiti: anviwon 2 680 mèt.",
 "Le pic la Selle, dans le Sud-Est, est le plus haut sommet d'Haïti, à environ 2 680 mètres."],
["Haiti shares the island of Hispaniola with the Dominican Republic. Haiti is on the western third of the island.",
 "Ayiti pataje zile Ispayola a ak Repiblik Dominikèn. Ayiti sou yon tyè lwès zile a.",
 "Haïti partage l'île d'Hispaniola avec la République dominicaine. Haïti occupe le tiers ouest de l'île."],
["The ceremony of Bois Caïman, in August 1791, is remembered as the start of the Haitian Revolution.",
 "Seremoni Bwa Kayiman, nan mwa out 1791, se li yo sonje kòm kòmansman Revolisyon Ayisyen an.",
 "La cérémonie du Bois-Caïman, en août 1791, est considérée comme le début de la Révolution haïtienne."],
["Jean-Jacques Dessalines declared Haiti's independence in the city of Gonaïves.",
 "Jan-Jak Desalin te pwoklame endepandans Ayiti nan vil Gonayiv.",
 "Jean-Jacques Dessalines a proclamé l'indépendance d'Haïti dans la ville des Gonaïves."],
["More than 500 volunteers from Saint-Domingue (today's Haiti) fought for American independence at the Siege of Savannah in 1779.",
 "Plis pase 500 volontè ki soti Sen Domeng (Ayiti jodi a) te goumen pou endepandans Ameriken nan batay Savannah an 1779.",
 "Plus de 500 volontaires de Saint-Domingue (l'actuelle Haïti) ont combattu pour l'indépendance américaine au siège de Savannah en 1779."],
["In 1815 and 1816, Haitian President Alexandre Pétion gave Simón Bolívar ships, weapons and soldiers to free South America.",
 "An 1815 ak 1816, Prezidan Aleksann Petyon te bay Simon Boliva bato, zam ak sòlda pou libere Amerik di Sid.",
 "En 1815 et 1816, le président haïtien Alexandre Pétion a donné à Simón Bolívar des navires, des armes et des soldats pour libérer l'Amérique du Sud."],
["The Sans-Souci Palace in Milot was the royal palace of King Henri Christophe. Its ruins are a UNESCO World Heritage Site.",
 "Palè Sansousi nan Milo te palè wa Anri Kristòf. Ras li yo sou lis Eritaj Mondyal UNESCO.",
 "Le palais Sans-Souci, à Milot, était le palais royal du roi Henri Christophe. Ses ruines sont classées au patrimoine mondial de l'UNESCO."],
["The national anthem, “La Dessalinienne”, was written by Justin Lhérisson in 1904, for 100 years of independence.",
 "Im nasyonal la, “La Dessalinienne”, se Jistin Leriso ki te ekri l an 1904, pou 100 an endepandans.",
 "L'hymne national, « La Dessalinienne », a été écrit par Justin Lhérisson en 1904, pour le centenaire de l'indépendance."],
["Kompa music was made popular in the 1950s by Nemours Jean-Baptiste, and it is still the beat of every Haitian party.",
 "Mizik konpa te vin popilè nan ane 1950 yo gras a Nemou Jan Batis, e se toujou li ki fè tout fèt ayisyen danse.",
 "La musique kompa a été popularisée dans les années 1950 par Nemours Jean-Baptiste, et elle rythme toujours les fêtes haïtiennes."],
["Haitian painting became famous around the world after the Centre d'Art opened in Port-au-Prince in 1944.",
 "Penti ayisyen te vin konnen nan lemonn antye apre Sant Da te louvri Pòtoprens an 1944.",
 "La peinture haïtienne est devenue célèbre dans le monde entier après l'ouverture du Centre d'Art à Port-au-Prince en 1944."],
["Jacmel is known for its colorful Carnival and its handmade papier-mâché masks.",
 "Jakmèl popilè pou kanaval koulè li ak mask papye mache moun fè ak men.",
 "Jacmel est connue pour son carnaval coloré et ses masques en papier mâché faits à la main."],
["Bassin Bleu, in the mountains near Jacmel, is a chain of turquoise pools and waterfalls.",
 "Basen Ble, nan mòn toupre Jakmèl, se yon seri basen dlo ble tankou turkwaz ak ti chit dlo.",
 "Le Bassin Bleu, dans les montagnes près de Jacmel, est une suite de bassins turquoise et de cascades."],
["Étang Saumâtre (Lake Azuei), near the border, is the largest lake in Haiti.",
 "Letan Somat (lak Azyèy), toupre fwontyè a, se pi gwo lak Ayiti.",
 "L'étang Saumâtre (lac Azuei), près de la frontière, est le plus grand lac d'Haïti."],
["Toussaint Louverture, born into slavery, became the great leader of the Haitian Revolution.",
 "Tousen Louvèti, ki te fèt esklav, te vin gwo chèf Revolisyon Ayisyen an.",
 "Toussaint Louverture, né esclave, est devenu le grand chef de la Révolution haïtienne."],
["Haiti's money is called the gourde, and Haitians often count in “dola” (5 gourdes = 1 Haitian dollar).",
 "Lajan Ayiti rele goud, e Ayisyen konn konte an “dola” (5 goud = 1 dola ayisyen).",
 "La monnaie d'Haïti est la gourde, et les Haïtiens comptent souvent en « dollars haïtiens » (5 gourdes = 1 dollar haïtien)."]
];
