// Towns from the original Lakaymwen.com registration page
window.LAKAYMWEN_TOWNS = [
"Abricot",
"Anse-à-Foleur",
"Anse-à-Galets",
"Anse-à-Pitre",
"Anse-à-Veau",
"Anse-d'Hainault",
"Anse-Rouge",
"Aquin",
"Arcahaie",
"Arniquet",
"Bahon",
"Baie-de-Henne",
"Bainet",
"Baradères",
"Bas-Limbé",
"Bassin Bleu",
"Beaumont",
"Belladère",
"Belle-Anse",
"Bombardopolis",
"Bonbon",
"Borgne",
"Boucan Carré",
"Cabaret",
"Camp-Perrin",
"Cap-Haîtien",
"Capotille",
"Caracol",
"Carice",
"Carrefour",
"Cavaillon",
"Cayes",
"Cayes-Jacmel",
"Cerca Cavajal",
"Cerca-la-Source",
"Chambelan",
"Chansolme",
"Chantal",
"Chardonnière",
"Cité Soleil",
"Corail",
"Cornillon",
"Côte-de-Fer",
"Côteaux",
"Croix-des-Bouquets",
"Dame-Marie",
"Delmas",
"Desdunes",
"Dessalines",
"Dondon",
"Ennery",
"Ferrier",
"Fond-des-Blancs",
"Fond-des-Nègres",
"Fond-Parisien",
"Fonds Verrettes",
"Fort-Liberté",
"Furcy",
"Gantier",
"Gonaïves",
"Grand-Bassin",
"Grand-Bois",
"Grand-Gôave",
"Grand-Gosier",
"Grande Rivière du Nord",
"Grande Saline",
"Grande-Anse",
"Gressier",
"Gros Morne",
"Hinche",
"Iles-à-Vache",
"Jacmel",
"Jean-Rabel",
"Jérémie",
"Kenscoff",
"L'Acul-du-Nord",
"L'Artibonite",
"L'Asile",
"L'Estère",
"La Chapelle",
"La Gonâve",
"La Tortue",
"La Victoire",
"Lascahobas",
"Léogane",
"Les Anglais",
"Les Irois",
"Les Trois Rivières",
"Limbé",
"Limonade",
"Maïssade",
"Maniche",
"Marigot",
"Marmelade",
"Milot",
"Miragoâne",
"Mirebalais",
"Môle Saint-Nicolas",
"Mombin-Crochu",
"Mont-Organisé",
"Moron",
"Ouanaminthe",
"Perches",
"Pestel",
"Pétion-Ville",
"Petit Trou de Nippes",
"Petit-Gôave",
"Petite Rivière de l'Artibonite",
"Petite Rivière de Nippes",
"Petite-Anse",
"Phaeton",
"Pignon",
"Pilate",
"Plaine du Nord",
"Plaisance",
"Pointe à Raquette",
"Port-à-Piment",
"Port-au-Prince",
"Port-de-Paix",
"Port-Margot",
"Port-Salut",
"Quartier Morin",
"Ranquitte",
"Roche-à-Bateau",
"Roseau",
"Saint-Jean du Sud",
"Saint-Louis du Nord",
"Saint-Louis du Sud",
"Saint-Marc",
"Saint-Michel de l'Attalaye",
"Saint-Michel-du-Sud",
"Saint-Raphaël",
"Sainte-Suzanne",
"Saut-d'eau",
"Savanette",
"Silbert",
"Tabarre",
"Terre Neuve",
"Terrier Rouge",
"Thiotte",
"Thomassique",
"Thomazeau",
"Thomonde",
"Tiburon",
"Torbeck",
"Trou-du-Nord",
"Trouin",
"Vallée de Jacmel",
"Vallière",
"Verrettes",
"Vieux-Bourg-d'Acquin"
];
